#config_version=6

coils:

# Board 1 - Cabinet

  c_launch_light:
    number: b_cabinet-2
    allow_enable: true
    default_hold_power: 1
  c_start_light:
    number: b_cabinet-3
    allow_enable: true
    default_hold_power: 1
  c_shaker:
    number: b_cabinet-1
    allow_enable: true
    default_pulse_ms: 1
    default_hold_power: 0.125

# Board 2 - Lower Mini


  c_flipper_l:
    number: b_main-1
    default_pulse_ms: 20
    allow_enable: true
    default_hold_power: 1
    
  c_flipper_r:
    number: b_main-7
    default_pulse_ms: 20
    allow_enable: true
    default_hold_power: 1
    
  c_trough:
    number: b_main-0
    default_pulse_ms: 20
    default_pulse_power: 1

  c_pop:
    number: b_main-4
    default_pulse_ms: 12

  c_sling_l:
    number: b_main-3
    default_pulse_ms: 12
    default_pulse_power: 0.8
  c_sling_r:
    number: b_main-6
    default_pulse_ms: 15
  c_vuk:
    number: b_main-5
    default_pulse_ms: 11
    
  c_drop:
    number: b_main_2-0
    default_pulse_ms: 25