#config_version=6

hardware:
  platform: fast
  

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default 


fast:
  net:
    port: com3
    controller: neuron
    io_loop:
      b_head:
        model: FP-I/O-0804
        order: 1
      b_cabinet:
        model: FP-I/O-0804
        order: 2
      b_main:
        model: FP-I/O-3208
        order: 3
      b_main_2:
        model: FP-I/O-0804
        order: 4
        
  exp:
    port: com5
    boards: 
      pf:
        model: FP-EXP-0081
      neu:
        model: FP-EXP-2000
        
config:

 - modes.yaml
 - lights.yaml
 - switches.yaml
 - coils.yaml
 - devices.yaml
 - player_vars.yaml
 - misc.yaml  