#config_version=6
mode:
  start_events: room_change_enabled
  stop_events: room_change_disabled
  events_when_started: room_change_end_disabled
  priority: 200

shots:

shows:
  shaker_spinner:
    - duration: 100ms
      coils:
        c_shaker: enable
    - duration: 1s
      coils:
        c_shaker: disable
        
  sling_flash_l:
    - lights:
        l_sling_l: red
      duration: 100ms
    - lights:
        l_sling_l: off
  sling_flash_r:
    - lights:
        l_sling_r: red
      duration: 100ms
    - lights:
        l_sling_r: off
        
  pop_flash:
    - lights:
        popflash: red
      duration: 100ms
    - lights:
        popflash: off
        
shots:

  r_pop:
   switch: s_pop
   profile: sp_base

  r_sling_l:
   switch: s_sling_l
   profile: sp_base
  r_sling_r:
   switch: s_sling_r
   profile: sp_base
   
  r_h:
    switch: s_h
    profile: sp_base 
    show_tokens:
      led: l_inlane_l
  r_o:
    switch: s_stationary_o
    profile: sp_base
    show_tokens:
      led: l_target_l
  r_u:
    switch: s_stationary_u
    profile: sp_base
    show_tokens:
      led: l_target_mid_l
  r_s:
    switch: s_stationary_s
    profile: sp_base
    show_tokens:
      led: l_target_r
  r_e:
    switch: s_e
    profile: sp_base 
    show_tokens:
      led: l_inlane_r

  r_ramp_r:
    hit_events: ss_ramp_r_hit
    profile: sp_base
    show_tokens:
      led: l_arrow_ramp_r
      led2: l_circle_ramp_r
  r_ramp_l:
    hit_events: ss_ramp_l_hit
    profile: sp_base
    show_tokens:
      led: l_arrow_ramp_r
      led2: l_circle_ramp_r
      
  r_vuk:
    switch: s_vuk
    profile: sp_base
    show_tokens:
      led: l_vuk_arrow_bot
      led2: l_vuk_square_bot
  r_vuk_bank:
    hit_events: ss_vuk_bank_hit
    profile: sp_base
    show_tokens:
      led: l_vuk_arrow_top
      led2: l_vuk_square_top
      
  r_right_orbit:
    hit_events: ss_right_orbit_hit
    profile: sp_base
    show_tokens:
      led: l_arrow_loop
      led2: l_circle_loop
      
  r_stationary_back:
    switch: s_drop
    profile: sp_base 
    show_tokens:
      led: l_knife
      led2: l_circle_knife
      led3: l_big_arrow_b
      
      
shot_profiles:
  sp_base:
      states:
      - name: state_base
        show: "off"
      
  
sequence_shots:
    
  ss_ramp_r:
    switch_sequence: s_ramp_r, s_ramp_complete
    sequence_timeout: 2s
  ss_ramp_l:
    switch_sequence: s_ramp_l, s_ramp_complete
    sequence_timeout: 2s
  ss_vuk_bank:
    switch_sequence: s_stationary_s, s_vuk
    sequence_timeout: 1s
  ss_right_orbit:
    switch_sequence: s_spinner, s_e
    sequence_timeout: 5s
  
  
variable_player:

  r_sling_l_hit:
    score: 10
  r_sling_r_hit:
    score: 10
  r_pop_hit:
    score: 50
  r_h_hit:
    score: 100
  r_o_hit:
    score: 100
  r_u_hit:
    score: 100
  r_s_hit:
    score: 100
  r_e_hit:
    score: 100
  r_stationary_back_hit:
    score: 200
    
  change_room_living_room:
    current_room:
      string: LIVING ROOM
  change_room_basement:
    current_room:
      string: BASEMENT
  change_room_that_room:
    current_room:
      string: THAT ROOM
  change_room_bed_room:
    current_room:
      string: BED ROOM
  change_room_kitchen:
    current_room:
      string: KITCHEN


    



show_player:
  ball_started: gi_kitchen_on
  r_pop_hit:
    pop_flash:
      loops: 0
  r_sling_l_hit: 
    sling_flash_l:
      loops: 0
  r_sling_r_hit: 
    sling_flash_r:
      loops: 0