#config_version=6
mode:
  start_events: room_change_enabled
  stop_events: room_change_enabled, secondary_modes_disabled
  priority: 300

shots:

  
  r_ramp_change_r:
    hit_events: ss_ramp_r_hit
    profile: sp_room_change
    show_tokens:
      led: l_circle_ramp_r
  r_ramp_change_l:
    hit_events: ss_ramp_l_hit
    profile: sp_room_change
    show_tokens:
      led: l_circle_ramp_r